version: "3.8"

services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: api-monitoring-rabbitmq
  #   hostname: rabbitmq
  #   volumes:
  #     - ./data/rabbitmq:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file:
  #     - .env

  redis:
    image: redis:latest
    container_name: api-monitoring-redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  postgres:
    image: postgres:latest
    container_name: api-monitoring-backend-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-tier

  mongodb:
    image: mongo:latest
    container_name: api-monitoring-notifications-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  postgres-db:
    driver: local
