### Get resources
GET http://localhost:8080/api/resources


### Get resources by name
GET http://localhost:8080/api/resources?name=User%20ser


### Create resource
POST http://localhost:8080/api/resources
Content-Type: application/json

{
    "name": "Order registration",
    "url": "http://localhost:3002/api/health",
    "checkFrequency": 30000
}


### Update resource
PATCH http://localhost:8080/api/resources/6eb43d5f-c9a1-449d-b97d-5d21879788ea
Content-Type: application/json

{
  "name": "user registration service",
  "url": "http://localhost:3001",
  "checkFrequency": 56400000,
  "description": "user registration service",
  "accessToken": "coffee"
}


### Delete resources by name
DELETE http://localhost:8080/api/resources/a3e22e03-0da3-493b-87a7-ff1bf858b4e7